### ISSUE TITLE
handle occasional error in API

### ISSUE THREAD

**Issue by idcrook** [idcrook/timetemp#1]
received following error which resulted is fatal exception

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/forecastio/models.py", line 103, in __getattr__
    return self.d[name]
KeyError: 'temperature'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./weather_logging_phant3.py", line 278, in <module>
    print(currently.temperature)
  File "/usr/local/lib/python3.5/dist-packages/forecastio/models.py", line 107, in __getattr__
    " or is not available for this forecast".format(name)
forecastio.utils.PropertyUnavailable: Property 'temperature' is not valid or is not available for this forecast
```

**Comment by idcrook** [comment]
PR #2 resolved
